[psql]
dbname     = "golang-postgres-graphql-starter"
host       = "localhost"
port       = 5432
user       = "killabyss"
pass       = "password"
sslmode    = "disable"
whitelist = [
    "todos",
    "users"
]